[project]
name = "ft-magic-flags"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cirq>=1.4.1",
    "stim>=1.14.0",
]
